### ISSUE TITLE
Feature Request: Option to specify Channel Shutdown timeout

### ISSUE THREAD

**Issue by steverawlins-zebra** [zalopay-oss/jmeter-grpc-request#122] opened 2022-06-15 16:52 UTC
### Discussed in https://github.com/zalopay-oss/jmeter-grpc-request/discussions/121

<div type='discussions-op-text'>

<sup>Originally posted by **steverawlins-zebra** June 15, 2022</sup>
We have discovered, during high-volume testing (more than 1000 messages per second), CHANNEL SHUTDOWN problems within jmeter-grpc-request.  Furthermore, once a CHANNEL SHUTDOWN triggers, the remainder of the test is useless - when we hit a problem, it's "game over" and what follows is nothing but a stream of CHANNEL SHUTDOWNs.

Please add a configuration option allowing us to increase that channel-shutdown timeout from the hard-coded 5, to a larger number such as 60 (seconds)

Thank you

P.S. The basis for our idea comes from examining the code in    `jmeter-grpc-request/src/main/java/vn/zalopay/benchmark/core`

```
 public void shutdownNettyChannel() {
        try {
            if (channel != null) {
                channel.shutdown();
                channel.awaitTermination(5, TimeUnit.SECONDS);
            }
        } catch (InterruptedException e) {
            throw new RuntimeException("Caught exception while shutting down channel", e);
        }
    }
```
</div>

**Comment by minhhoangvn** [comment] 2022-06-16 05:49
Can I know do you use the for-loop with the gRPC sampler, currently, this issue maybe happen if we use the for-loop with the gRPC sampler, so, when the channel is shut down, it can't send a request anymore. Please also provide your sample JMeter test plan to reproduce that issue for debugging purpose :D

**Comment by steverawlins-zebra** [comment] 2022-06-16 14:49
Thank you.  Our plan is attached.  I changed the extension from jmx so that I could attach it here
[ForZalopay.txt](https://github.com/zalopay-oss/jmeter-grpc-request/files/8919896/ForZalopay.txt)
.

**Comment by steverawlins-zebra** [comment] 2022-06-16 17:05
here is our Test Pla
[ForZalopay.txt](https://github.com/zalopay-oss/jmeter-grpc-request/files/8920961/ForZalopay.txt)
n

**Comment by alphadeepak** [comment] 2022-06-20 13:40
@minhhoangvn  Thanks for this feature !
Wanted some info regarding the channel implementation. Are the channels being re-used or are we creating different channels for each of the request / concurrent user scenario?

**Comment by alphadeepak** [comment] 2022-06-21 06:47
@minhhoangvn  thanks !

**Comment by Renu-Lamba** [comment] 2022-06-21 07:05
Hi @minhhoangvn , We are giving channel await termination time 20 min and still getting the channel shutdown issue , can you please suggest anything on this .

The test plan have 200 users with a duration of 30 min , We have observed that channel shutdown is getting invoked after 150+ users are ramped up.

Please note that its for same test plan shared by @steverawlins-zebra .

**Comment by Renu-Lamba** [comment] 2022-06-22 08:12
@minhhoangvn  thanks for sharing the info .

We keep getting the "GRPC Request - 500 : Exception: io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdown invoked" error when number of users are above 100 , this issue never happens when users are less than 100.

Can you please suggest on this why its happening . We have given good amount for channel shutdown and deadline timeout to 20 min .

**Comment by minhhoangvn** [comment] 2022-06-22 13:26
@Renu-Lamba, the error is related to your backend reaching the maximum connections it can establish. The gRPC sampler will have status code 500(response time is too long, the server can't establish a new connection) and close the channel to start a new interaction with the current virtual user. It would be best if you had a dashboard to monitor your backend service and some key metrics indicators that you can use to analyze current active connections, throughput (RPS/TPS), and p99 latency. So I think we can close this issue because should be out of the scope of the gRPC JMeter sampler

**Closed** 2022-06-26 04:16 UTC

**Comment by Renu-Lamba** [comment] 2022-06-28 18:21
@minhhoangvn  ,Thanks for all the help and suggestions ,Much appreciated

**Comment by waleedconcurrent** [comment] 2023-09-18 09:42
@minhhoangvn I am also facing the same issue, I am only using a single user, and once the request fails with a valid error all the subsequent requests fail and the response is "Channel shutdown invoked". 
If I stop and start the script again it starts to work and then fails again after the first failure from the server side.
